name: Kata Indexer

on: [push]

jobs:
  generate-kata-index:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Generate index and push back to repo
      run: |
        cp docs/README.template ./README.md
        cd solutions
        FILES=$(find * -type f \( -iname \*.py -o -iname \*.js \))
        for f in $FILES
        do
          DESC=$(sed -n '1p' < $f | cut -c 3-)
          URL=$(sed -n '2p' < $f | cut -c 3-)
          TITLE=$(echo "$f" | cut -f 1 -d '.')

          if [ -n "$DESC" ] && [ -n "$URL" ]
          then
            echo "- $TITLE - [$DESC](https://github.com/jsjohnstone/codewars/blob/master/solutions/$f) \[[kata]($URL)\]" >> ../README.md
          fi

          unset DESC
          unset URL

        done

        cd ..

        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

        git add README.md
        git commit -m "Automatically index katas and update README"
        git push
      
